FROM node:20-alpine

WORKDIR /app

# Copy package.json and install dependencies
COPY package.json package-lock.json* ./
RUN yarn

# Copy the rest of the application
COPY . .

# Expose the port the app will run on
EXPOSE 3000

# Start the development server
CMD ["yarn", "run", "dev"]
